name: CD

on:
  workflow_run: 
    workflows: [ "CI" ]
    types:
      - completed
    
jobs:
  build:

    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: |
          cd /home/ubuntu/apps/fatatu/
          docker compose down
          docker rm undermad/fatatu || true
          docker rm undermad/fatatu-front || true
          docker rmi undermad/fatatu || true
          docker rmi undermad/fatatu-front || true
          docker compose up -d
      
      

  
  